Change git hash regex to match abbrevCommit
banga/blog pull request #1
Opened 2020-03-02 14:08 UTC by omBratteng

The default hash length of abbrevCommit is 7, so I updated the regex to `[0-9a-f]{7,40}`, I've tested it on my computer and it works

2020-12-31 22:58 UTC, banga requested changes
Thanks! Sorry never got a notification for this PR

2020-12-31 22:58 UTC, banga commented on _posts/2020-03-01-little-known-features-of-iterm2.markdown
> +3. Click the `+` button to add a new rule and set the `Regular Expression` to `[0-9a-f]7,40}`
I think you missed the opening `{` here

2021-01-05 10:29 UTC, omBratteng commented on _posts/2020-03-01-little-known-features-of-iterm2.markdown
> +3. Click the `+` button to add a new rule and set the `Regular Expression` to `[0-9a-f]7,40}`
Looks like it. I seem to have deleted my fork of the repo, so I'll close this PR and opened #3

2021-01-05 10:29 UTC, closed without merging

2021-01-05 10:29 UTC, omBratteng commented
See #3